[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ophix-conf-client"
version = "2026.05.18.01"
description = "Configuration client for Ophix Project Servers"
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
authors = [
    { name = "Ophix Project" }
]
dependencies = [
    "ophix-client-core>=2026.05.12.01",
    "requests>=2.28",
    "python-dotenv>=1.0",
    "distro>=1.8",
    "urllib3>=2.0",
    "venv-cmds>=2026.05.01.04",
]

[project.scripts]
conf-client = "conf_client.cli:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
